### ISSUE TITLE
Issue 

### ISSUE THREAD

**Issue by warhead-wolf** [KenwoodFox/EG-207-CCEMS#7]
Issues getting library on windows

**Comment by KenwoodFox** [comment]
I use the arduino cli to handle library downloads, but for you on windows it may be easier to use the builtin library manager.

All of the libraries are specified in `arduino/lab1/requirements.txt` just copy them into the library manager like this 
![image](https://user-images.githubusercontent.com/31870999/134432066-5d638f74-2c6e-42ed-81eb-64414194faaf.png)

**Comment by KenwoodFox** [comment]
Im closing this because i think we fixed it, yeah?
